---
functional:
  - Пользователь должен иметь возможность авторизоваться на сервисе.
  - Пользователь должен иметь возможность создать новую игру с другим игроком.
  - Пользователь должен иметь возможность создать новую игру с ботом.
  - Пользователь должен иметь возможность создать новую игру с другом.
  - Пользователь должен иметь возможность выбрать уровень игры.
  - Пользователь должен иметь возможность выбрать время на каждую игру.
  - Пользователь должен иметь возможность выбрать тип игры по тэгам.
  - Пользователь должен иметь возможность проверить выполнение кода при игре.
  - Когда один из игроков находит верное решение, обоим игрокам высвечивается модальное окно, где написано, кто является победителем этой игры.
  - Пользователь должен иметь возможность перезайти в игру, пока она не закончилась.
  - Пользователь должен иметь возможность сыграть в пробную игру без регистрации.
  - Пользователь должен иметь возможность создать турнир.
  - Пользователь должен иметь возможность присоединиться к существующему турниру.
  - Пользователь при решении задач должен увеличивать свой уровень в таблице Leaderboard.
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть удобным на мобильном устройстве.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
implicit:
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей).
